# Generated by Django 3.1.5 on 2022-05-25 03:21

import brain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('storytitle', models.CharField(max_length=100)),
                ('story', models.CharField(max_length=100)),
                ('patient_img', models.ImageField(blank=True, null=True, upload_to=brain.models.patientimg)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Story',
            },
        ),
    ]
