# Generated by Django 3.1.5 on 2022-05-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0004_story_hospital_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
