# Generated by Django 3.1.5 on 2022-05-05 09:35

import brain.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctorformfill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doctor_nid', models.IntegerField()),
                ('doctor_img', models.ImageField(blank=True, null=True, upload_to=brain.models.doctorimg)),
                ('disease_name', models.CharField(choices=[('Meningioma', 'Meningioma'), ('Pituitary Adenoma', 'Pituitary Adenoma'), ('Craniopharyngioma', ' Craniopharyngioma'), ('Schwannoma', 'Schwannoma')], max_length=100)),
                ('details', models.CharField(max_length=100)),
            ],
        ),
    ]
